# Generated by Django 4.2.4 on 2024-05-02 12:52

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("webInterface", "0002_indexer_is_title"),
    ]

    operations = [
    ]
