# Generated by Django 4.2.4 on 2024-05-02 14:15

from django.db import migrations
from SearchEngine.webInterface.spider import load_initial_data

class Migration(migrations.Migration):

    dependencies = [
        ("webInterface", "0003_auto_20240502_2052"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
