# Generated by Django 4.2.4 on 2024-05-02 14:15

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("webInterface", "0003_auto_20240502_2052"),
    ]

    operations = [
    ]
