# Generated by Django 4.2.4 on 2024-05-10 05:43

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("webInterface", "0004_auto_20240502_2215"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopKeywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.IntegerField()),
                ("rank", models.IntegerField()),
                (
                    "keyword_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webInterface.keywords",
                    ),
                ),
                (
                    "page_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webInterface.pages",
                    ),
                ),
            ],
            options={
                "unique_together": {("page_id", "rank")},
            },
        ),
    ]
