# Generated by Django 4.2.4 on 2024-05-10 07:50

from django.db import migrations
from webInterface.spider import load_initial_data

class Migration(migrations.Migration):

    dependencies = [
        ("webInterface", "0005_topkeywords"),
    ]

    operations = [        
        migrations.RunPython(load_initial_data),
    ]
